database:
  # Available types: SQLite, MySQL
  type: MySQL

  # Specific to MySQL, leave blank with SQLite
  host: 172.18.0.1
  database: Skyblock
  username: u28_BkBAJgUhJp
  password: u^8.^zRXV53eVLpW@Q+rNGe9
  port: 3306