database:
  # Available types: SQLite, MySQL
  type: MySQL

  # Specific to MySQL, leave blank with SQLite
  host: localhost
  database: Skyblock
  username: username
  password: password
  port: 3306